# https://prettier.io/docs/en/configuration.html
# https://prettier.io/docs/en/options.html
# https://github.com/prettier/prettier-vscode#default-formatter
---
trailingComma: "es5"
tabWidth: 4
semi: false
singleQuote: true
...